"""
Injection-recovery tests for DustEvolutionModel.

Design mirrors test_pah_bayesian_recovery.py: three escalating tiers,
all using synthetic data generated by simulate_stacked_dataframe so no
real FITS or catalog files are required.

Key insight encoded in these tests
------------------------------------
The warm/cold decomposition is *individually* under-constrained per bin
above z~3 (even with evolving T_c, the warm component peak washes into
the cold component tail when only SPIRE/SCUBA2 are available).  But the
global warm-fraction coefficients [a0, a_z, a_M] are *jointly* identifiable
because the fitter sees the systematic z-trajectory of the SED shape across
ALL bins simultaneously.

Tier 2b (the critical negative test) demonstrates the per-bin failure mode:
a single-component greybody fit at high z returns an inflated T_dust.  This
is the ALMA-vs-stacking diagnostic in simulation form.

Bin grid (cosmos25_mass_sigma_sfr.toml analogue)
-------------------------------------------------
  z bins    : 0.5, 1.0, 1.5, 2.0, 3.0, 5.0  (5 bins, midpoints used)
  M* bins   : 9.0–10.3, 10.3–10.8, 10.8–12.0  (3 bins)
  σ_SFR bins: −1 to −0.25, −0.25 to 0.25, 0.25 to 1.0  (3 bins)
  Total: 5 × 3 × 3 = 45 property bins (too slow for CI); tests use 2D grids.
"""

import numpy as np
import pytest

from simstack4.dust_evolution import (
    DustEvolutionModel,
    warm_fraction,
    warm_temperature,
    _greybody_sed,
    _peak_wavelength_um,
    COSMOS_BANDS,
)


# ---------------------------------------------------------------------------
# Shared constants
# ---------------------------------------------------------------------------

# True global parameters: [T_c, T_w0, c_sigma, a0, a_z, a_M, a_sigma]
#   T_c = 30 K cold dust (V22 low-z baseline)
#   T_w0 = 55 K warm dust at log_σ_SFR = 0
#   c_sigma = 5 K per dex in σ_SFR  (physical: radiation field intensity)
#   a0 = −0.5  → f_w ≈ 38% at z=0.75, log_M*=10.5 — clearly above 3% noise floor
#   a_z = 0.10 → moderate z evolution of warm fraction
#   a_M = 0.0  → no mass dependence (simple case; used in most tests)
#   a_sigma = 0.0 → no σ_SFR dependence on f_w (T_w dependence via c_sigma suffices)
THETA_TRUE = np.array([30.0, 55.0, 5.0, -0.5, 0.10, 0.0, 0.0])

# z × σ_SFR grid (2D for speed; 6 z bins × 3 σ_SFR bins = 18 property bins)
Z_MIDS     = [0.75, 1.25, 1.75, 2.5, 4.0, 5.5]
SIGMA_MIDS = [-0.625, 0.0, 0.625]    # low / mid / high σ_SFR
LOG_M_STAR = 10.5                     # fixed mass for 2D tests

BIN_GRID_2D = [
    {"bin_id": i * len(SIGMA_MIDS) + j,
     "z": z,
     "log_M_star": LOG_M_STAR,
     "log_sigma_sfr": sig}
    for i, z in enumerate(Z_MIDS)
    for j, sig in enumerate(SIGMA_MIDS)
]

# For M*-σ_SFR tests: vary M*, σ_SFR, AND z so a_z is identifiable alongside a_M.
# Fixed-z grids make a0 and a_z perfectly degenerate (only a0+a_z*z is observable).
LOG_M_VALS  = [9.5, 10.5, 11.2]
Z_VALS_3D   = [0.75, 2.5]            # two z points to break the a0/a_z degeneracy
BIN_GRID_3D = [
    {"bin_id": (i_z * len(LOG_M_VALS) + i_m) * len(SIGMA_MIDS) + j,
     "z": z,
     "log_M_star": m,
     "log_sigma_sfr": sig}
    for i_z, z in enumerate(Z_VALS_3D)
    for i_m, m in enumerate(LOG_M_VALS)
    for j, sig in enumerate(SIGMA_MIDS)
]

# Cold amplitudes — mild z-trend mimicking L_IR evolution
A_C_TRUE = np.array([
    1.0 + 0.3 * i for i, _ in enumerate(BIN_GRID_2D)
])
A_C_TRUE_3D = np.ones(len(BIN_GRID_3D))

MCMC_FAST  = dict(n_steps=300,  n_burn=100, n_walkers=32, progress=False, verbose=False)
MCMC_STD   = dict(n_steps=2000, n_burn=500, n_walkers=32, progress=False, verbose=False)
MCMC_LONG  = dict(n_steps=3000, n_burn=700, n_walkers=32, progress=False, verbose=False)

PARAM_TOL = 0.20   # 20% fractional tolerance on global parameters


@pytest.fixture(scope="module")
def dem():
    return DustEvolutionModel()


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------

def _check_global_params(result, theta_true, tol=PARAM_TOL, skip=(), tol_override=None):
    """Assert that each recovered global param is within tol × |truth|.

    Collects all results before raising so a single run shows every param.
    tol_override: dict mapping param name → tolerance, takes precedence over tol.
    """
    names = result.param_names
    lines = []
    any_fail = False
    for name, truth, rec, err in zip(names, theta_true, result.theta_global, result.theta_err):
        if name in skip:
            continue
        t = (tol_override or {}).get(name, tol)
        if abs(truth) < 1e-6:
            fail = abs(rec) >= t
            lines.append(f"  {name}: truth≈0, rec={rec:.3f} ({'FAIL' if fail else 'PASS'}, tol={t})")
        else:
            frac = abs(rec - truth) / abs(truth)
            fail = frac >= t
            lines.append(
                f"  {name}: truth={truth:.3f}, rec={rec:.3f}, "
                f"frac_err={frac:.3f} ({'FAIL' if fail else 'PASS'}, tol={t})"
            )
        any_fail = any_fail or fail
    if any_fail:
        raise AssertionError("Parameter recovery results:\n" + "\n".join(lines))


# ---------------------------------------------------------------------------
# Tier 1 — simulator consistency (no MCMC)
# ---------------------------------------------------------------------------

class TestSimulatorConsistency:
    """Check simulate_stacked_dataframe without running the sampler."""

    def test_positive_fluxes_low_z(self, dem):
        sim = dem.simulate_stacked_dataframe(
            BIN_GRID_2D[:3], THETA_TRUE, A_c_true=A_C_TRUE[:3], noise_scale=0.0,
        )
        df = sim["df"]
        for band in COSMOS_BANDS:
            col = df[band].dropna()
            if len(col) > 0:
                assert (col > 0).all(), f"{band}: non-positive flux at low z"

    def test_mips_dropout_above_z25(self, dem):
        sim = dem.simulate_stacked_dataframe(BIN_GRID_2D, THETA_TRUE, noise_scale=0.0)
        df = sim["df"]
        high_z = df[df["z"] > 2.5]
        assert high_z["MIPS_24"].isna().all(), "MIPS_24 should be NaN above z=2.5"

    def test_warm_fraction_increases_with_z(self, dem):
        sim = dem.simulate_stacked_dataframe(BIN_GRID_2D, THETA_TRUE, noise_scale=0.0)
        tp = sim["true_params"]
        fw = tp["fw_true"]
        # For our grid, bins 0,3,6,9,12,15 are at sigma_mid=0 for increasing z
        # Extract the middle-sigma slice
        idx_mid = [1 + j * len(SIGMA_MIDS) for j in range(len(Z_MIDS))]
        fw_by_z = fw[idx_mid]
        assert (np.diff(fw_by_z) > 0).all(), (
            f"f_w should increase with z; got {fw_by_z}"
        )

    def test_warm_temp_increases_with_sigma(self, dem):
        sim = dem.simulate_stacked_dataframe(BIN_GRID_2D, THETA_TRUE, noise_scale=0.0)
        tp = sim["true_params"]
        Tw = tp["Tw_true"]
        # First z-slice: bins 0, 1, 2 have increasing σ_SFR
        assert Tw[0] < Tw[1] < Tw[2], (
            f"T_w should increase with σ_SFR; got {Tw[:3]}"
        )

    def test_required_columns_present(self, dem):
        sim = dem.simulate_stacked_dataframe(BIN_GRID_2D, THETA_TRUE)
        df = sim["df"]
        for col in ["bin_id", "z", "log_M_star", "log_sigma_sfr"]:
            assert col in df.columns, f"Missing column: {col}"
        for band in COSMOS_BANDS:
            assert band in df.columns
            assert f"{band}_err" in df.columns

    def test_peak_wavelength_evolves_with_T(self):
        """λ_peak ≈ 3000/T — confirms evolving T shifts the peak correctly."""
        for T in [25, 35, 50, 70]:
            lam = _peak_wavelength_um(T, beta=1.8)
            expected = 3000.0 / T
            assert abs(lam - expected) / expected < 0.05, (
                f"T={T}K: λ_peak={lam:.1f} µm, expected ≈{expected:.1f} µm"
            )

    def test_fitter_initialises_without_error(self, dem):
        sim = dem.simulate_stacked_dataframe(
            BIN_GRID_2D[:6], THETA_TRUE, A_c_true=A_C_TRUE[:6], noise_scale=0.05,
        )
        result = dem.fit_dust_evolution(
            sim["df"], n_steps=60, n_burn=20, progress=False, verbose=False,
        )
        assert result is not None
        assert np.isfinite(result.acceptance_fraction)


# ---------------------------------------------------------------------------
# Tier 2 — MAP recovery (joint fit, all global params)
# ---------------------------------------------------------------------------

class TestGlobalParameterRecovery:
    """
    Joint fit recovers [T_c, T_w0, c_sigma, a0, a_z] within PARAM_TOL.
    a_M is fixed at 0 in these tests (see Tier 3 for the M*-σ_SFR separation).
    """

    def test_tc_and_fw_evolution_recovered(self, dem):
        """Main recovery test: T_c + f_w z-evolution at low noise.

        BIN_GRID_2D has fixed log_M*=10.5, so a_M is degenerate with a0
        (a0 + a_M·10.5 is identifiable but not each term separately).
        We fix a_M=0 so the chain has 6 well-identified parameters
        [T_c, T_w0, c_sigma, a0, a_z, a_sigma].
        """
        sim = dem.simulate_stacked_dataframe(
            BIN_GRID_2D, THETA_TRUE, A_c_true=A_C_TRUE, noise_scale=0.005,
        )
        result = dem.fit_dust_evolution(sim["df"], fix_a_M=True, **MCMC_STD)
        assert result is not None
        _check_global_params(result, THETA_TRUE)

    def test_cold_amplitude_positive(self, dem):
        """Recovered per-bin A_c must all be positive."""
        sim = dem.simulate_stacked_dataframe(
            BIN_GRID_2D, THETA_TRUE, A_c_true=A_C_TRUE, noise_scale=0.03,
        )
        result = dem.fit_dust_evolution(sim["df"], fix_a_M=True, **MCMC_STD)
        assert result is not None
        assert (result.A_c_per_bin > 0).all(), (
            f"Negative A_c: {result.A_c_per_bin}"
        )

    def test_warm_fraction_ordering_preserved(self, dem):
        """f_w(z_high) > f_w(z_low) at fixed σ_SFR — preserved by joint fit."""
        sim = dem.simulate_stacked_dataframe(
            BIN_GRID_2D, THETA_TRUE, A_c_true=A_C_TRUE, noise_scale=0.005,
        )
        result = dem.fit_dust_evolution(sim["df"], fix_a_M=True, **MCMC_STD)
        assert result is not None
        # Middle-sigma bins indexed at j=1 within each z-slice
        idx_mid = [1 + j * len(SIGMA_MIDS) for j in range(len(Z_MIDS))]
        fw_rec = result.f_w_per_bin[idx_mid]
        assert (np.diff(fw_rec) > 0).all(), (
            f"f_w ordering not preserved across z: {fw_rec}"
        )


# ---------------------------------------------------------------------------
# Tier 2b — the critical negative test: per-bin single-component failure
# ---------------------------------------------------------------------------

class TestPerBinSingleComponentBias:
    """
    Demonstrate that fitting a single-component greybody per bin at high z
    returns a biased (inflated) T_dust when a warm component is present.

    This is the simulation-level proof that the joint approach is necessary,
    not optional.  It also mirrors the V22 vs ALMA tension: V22 used the
    Herschel bands (which at z>3 are probing rest <100 µm where the warm
    component contributes), while ALMA data may probe rest 50-150 µm more
    directly.
    """

    def test_single_component_inflates_T_at_high_z(self, dem):
        """
        With a warm component present, single-component fits at z>3 return
        higher T_dust than the true T_c.

        Warm fraction design: a0=-2.0, a_z=0.3 gives:
          z=0.75: f_w ≈ 1.5% — modest warm contamination, T bias small
          z=2.50: f_w ≈ 6%  — growing bias
          z=5.50: f_w ≈ 45% — strong warm contamination, T bias large
        This z-gradient produces a clear low-z/high-z comparison.
        """
        from simstack4.greybody import Greybody

        # Weak warm at low z, strong at high z
        theta_warm = np.array([30.0, 60.0, 0.0, -2.0, 0.30, 0.0, 0.0])
        A_c_test = np.ones(len(BIN_GRID_2D))

        sim = dem.simulate_stacked_dataframe(
            BIN_GRID_2D, theta_warm, A_c_true=A_c_test, noise_scale=0.005,
        )
        df = sim["df"]
        T_c_true = 30.0

        gb = Greybody(fix_beta=True, beta_fixed=1.8, use_mcmc=False,
                      temperature_prior="flat", T_rest_max=90.0)

        T_fitted_low_z  = []
        T_fitted_high_z = []

        for _, row in df.iterrows():
            z = row["z"]
            waves, fluxes, errs = [], [], []
            for band in COSMOS_BANDS:
                if band == "MIPS_24":
                    continue   # exclude mid-IR: warm Wien tail saturates T at all z
                f = row.get(band, np.nan)
                e = row.get(f"{band}_err", np.nan)
                if np.isfinite(f) and np.isfinite(e) and e > 0 and f > 0:
                    waves.append(COSMOS_BANDS[band])
                    fluxes.append(f)
                    errs.append(e)

            if len(waves) < 3:
                continue

            sed_result = gb.fit_sed(
                np.array(waves), np.array(fluxes), np.array(errs), redshift=z,
            )
            if not (sed_result and sed_result.get("fit_success")):
                continue
            T_fit = sed_result.get("temperature_rest_frame")
            chi2 = sed_result.get("chi2_reduced", np.nan)
            if T_fit is None:
                continue

            if z < 1.5:
                T_fitted_low_z.append(T_fit)
            elif z > 3.5:
                T_fitted_high_z.append(T_fit)

        assert T_fitted_low_z, "No low-z bins fitted"
        assert T_fitted_high_z, "No high-z bins fitted"

        T_low  = np.median(T_fitted_low_z)
        T_high = np.median(T_fitted_high_z)

        # At low-z: f_w≈1.5% — warm bias is negligible, T_low ≈ T_c (may be slightly below).
        # At high-z: f_w≈45%, warm component peaks where SPIRE bands land → T inflated.
        # The scientifically important claims: high-z T is inflated AND bias grows with z.
        assert T_high > T_c_true, (
            f"High-z T_dust should exceed T_c={T_c_true}K due to warm bias; got {T_high:.1f}K"
        )
        assert T_high > T_low, (
            f"Warm bias must grow with z; T_low={T_low:.1f}K, T_high={T_high:.1f}K"
        )


# ---------------------------------------------------------------------------
# Tier 3 — M* and σ_SFR separation
# ---------------------------------------------------------------------------

class TestMassSigmaDecomposition:
    """
    Verify that a_M (mass dependence) and c_sigma (σ_SFR dependence of T_w)
    are separately recoverable when both vary.

    If posterior contours are elongated along a_M + c_sigma = const, a
    degeneracy exists and the simulator exposes it at COSMOS noise levels.
    """

    def test_sigma_ordering_preserved(self, dem):
        """T_w(high σ_SFR) > T_w(low σ_SFR) — recovered by the fitter."""
        sim = dem.simulate_stacked_dataframe(
            BIN_GRID_2D, THETA_TRUE, A_c_true=A_C_TRUE, noise_scale=0.03,
        )
        result = dem.fit_dust_evolution(sim["df"], fix_a_M=True, **MCMC_STD)
        assert result is not None
        # Within the first z-slice (bins 0, 1, 2), σ_SFR increases
        Tw_rec = result.T_w_grid[:3]
        assert Tw_rec[0] < Tw_rec[2], (
            f"T_w should increase with σ_SFR; got {Tw_rec}"
        )

    def test_mass_dependence_recovered(self, dem):
        """a_M ≠ 0: higher M* → higher f_w — recovered by joint fit on 3D grid.

        Uses a0=-1.5 (not THETA_TRUE's -0.5) so f_w stays in 30-75% range
        across the M* and z grid — both components contribute and the mass
        dependence is clearly visible in the SED shape.
        """
        # a0=-1.5 at z=0.75, M*=9.5: f_w≈33%; at z=2.5, M*=11.2: f_w≈74%
        theta_mass = np.array([30.0, 55.0, 5.0, -1.5, 0.10, 0.1, 0.0])

        sim = dem.simulate_stacked_dataframe(
            BIN_GRID_3D, theta_mass, A_c_true=A_C_TRUE_3D, noise_scale=0.005,
        )
        result = dem.fit_dust_evolution(sim["df"], fix_a_M=False, theta_init=theta_mass, **MCMC_LONG)
        assert result is not None
        # a_M recovered positive (sign check — theta_global is 5 or 6 params)
        a_M_idx = result.param_names.index("a_M")
        assert result.theta_global[a_M_idx] > 0, (
            f"a_M should be positive; got {result.theta_global[a_M_idx]:.3f}"
        )

    def test_zero_mass_dependence(self, dem):
        """On a 3D grid with true a_M=0, fitter should not pull a_M away from 0."""
        sim = dem.simulate_stacked_dataframe(
            BIN_GRID_3D, THETA_TRUE, A_c_true=A_C_TRUE_3D, noise_scale=0.03,
        )
        result = dem.fit_dust_evolution(sim["df"], fix_a_M=False, **MCMC_LONG)
        assert result is not None
        a_M_idx = result.param_names.index("a_M")
        a_M_rec = result.theta_global[a_M_idx]
        # Should not be strongly biased away from 0
        assert abs(a_M_rec) < 0.3, (
            f"a_M should be near 0; got {a_M_rec:.3f} — possible M*-σ_SFR degeneracy"
        )
