# Simstack4 Configuration File
# This replaces the INI format from simstack3 with more user-friendly TOML

[binning]
stack_all_z_at_once = true    # Stack all redshifts together (optimal but memory intensive)
add_foreground = true         # Add foreground layer of all 1's
crop_circles = true           # Draw circles around sources and flatten

[error_estimator]
write_simmaps = false         # Write simulated images at each wavelength
randomize = false             # For null-testing: shuffle (x,y) when building layers

[error_estimator.bootstrap]
enabled = true                # Use bootstrap method for error estimation
iterations = 5              # Number of bootstrap iterations
initial_seed = 1              # Seed for random shuffling (ensures consistency across bands)

# Top-level simple settings
cosmology = "Planck18"        # Options: "Planck15", "Planck18"

[output]
folder = "$PICKLESPATH/simstack/stacked_flux_densities"  # Environment variables supported
shortname = "cosmos25"      # Name for output folder

[catalog]
path = "$CATSPATH/cosmos"     # Path to catalog directory
file = "cosmos2020_FARMER.csv"  # Catalog filename

[catalog.astrometry]
ra = "ALPHA_J2000"                     # Column name for right ascension
dec = "DELTA_J2000"                   # Column name for declination

[catalog.classification]
split_type = "nuvrj"            # Options: "labels", "uvj", "nuvrj"

[catalog.classification.split_params.bins]
"NUV-R" = "restNUV-R"              # NUV-R color column name
"R-J" = "restR-J"                  # R-J color column name

[catalog.classification.redshift]
id = "lp_zBEST"                 # Column name for redshift
bins = [0.01, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 5.0, 6.0, 8.0, 10.0]  # Redshift bin edges

[catalog.classification.stellar_mass]
id = "lp_mass_med"                  # Column name for stellar mass
bins = [8.5, 9.5, 10.0, 10.5, 11.0, 12.0]  # Stellar mass bin edges



[maps.pacs_red]
wavelength = 160.0
color_correction = 1.0
path_map = "$MAPSPATH/cosmos/cutouts/COSMOS_PACS160_20160728_img_avg.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/COSMOS_PACS160_20160728_img_avg_noise.fits"

[maps.pacs_red.beam]
fwhm = 11.33
area_sr = 4.658e-09

[maps.spire_psw]
wavelength = 250.0
color_correction = 1.018
path_map = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PSW.signal.cutout.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PSW.noise.cutout.fits"

[maps.spire_psw.beam]
fwhm = 17.62

[maps.spire_pmw]
wavelength = 350.0
color_correction = 0.9914
path_map = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PMW.signal.cutout.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PMW.noise.cutout.fits"

[maps.spire_pmw.beam]
fwhm = 24.42

[maps.spire_plw]
wavelength = 500.0
color_correction = 0.9565
path_map = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PLW.signal.cutout.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PLW.noise.cutout.fits"

[maps.spire_plw.beam]
fwhm = 35.69

[maps.scuba]
wavelength = 850.0
color_correction = 1e-3
path_map = "$MAPSPATH/cosmos/cutouts/S2CLS_COSMOS_NMF_DR1_new_header.cutout.signal.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/S2CLS_COSMOS_NMF_DR1_new_header.cutout.noise.fits"

[maps.scuba.beam]
fwhm = 12.1