# Simstack4 Configuration File
# This replaces the INI format from simstack3 with more user-friendly TOML

[binning]
stack_all_z_at_once = true    # Stack all redshifts together (optimal but memory intensive)
add_foreground = true         # Add foreground layer of all 1's
crop_circles = true           # Draw circles around sources and flatten

[error_estimator]
write_simmaps = false         # Write simulated images at each wavelength
randomize = false             # For null-testing: shuffle (x,y) when building layers

[error_estimator.bootstrap]
enabled = true                # Use bootstrap method for error estimation
method="per_bin"             # "per_bin"
iterations = 5            # Number of bootstrap iterations
initial_seed = 1              # Seed for random shuffling (ensures consistency across bands)
split_fraction = 0.5

# Top-level simple settings
cosmology = "Planck18"        # Options: "Planck15", "Planck18"

[output]
folder = "$PICKLESPATH/simstack/stacked_flux_densities"  # Environment variables supported
shortname = "cosmos25"      # Name for output folder

[catalog]
path = "$CATSPATH/cosmos"     # Path to catalog directory
file = "cosmos2020_FARMER.csv"  # Catalog filename

[catalog.astrometry]
ra = "ALPHA_J2000"                     # Column name for right ascension
dec = "DELTA_J2000"                   # Column name for declination

[catalog.classification]
split_type = "nuvrj"            # Options: "labels", "uvj", "nuvrj"
bin_property_columns = ["lp_mass_med", "lp_SFR_med", "lp_sSFR_med"]

[catalog.classification.split_params.bins]
"NUV-R" = "restNUV-R"              # NUV-R color column name
"R-J" = "restR-J"                  # R-J color column name

[catalog.classification.binning.redshift]
id = "lp_zBEST"                 # Column name for redshift
# Run 0: 26 bins
#bins = [0.5, 0.65, 0.723, 0.835, 0.872, 0.959, 1.022, 1.111,
#        1.2, 1.263, 1.364, 1.458, 1.562, 1.675, 1.774, 1.883,
#        2.018, 2.168, 2.318, 2.468, 2.618, 2.768, 2.918, 3.068,
#        3.218, 3.368, 3.5]

# Run 1: 27 bins
#bins = [0.5, 0.55, 0.674, 0.76, 0.847, 0.901, 0.98, 1.052,
#        1.141, 1.221, 1.297, 1.395, 1.493, 1.6, 1.708, 1.81,
#        1.928, 2.068, 2.218, 2.368, 2.518, 2.668, 2.818, 2.968,
#        3.118, 3.268, 3.412, 3.5]

# Run 2: 27 bins
#bins = [0.5, 0.6, 0.699, 0.798, 0.86, 0.93, 1.001, 1.081,
#        1.17, 1.242, 1.33, 1.427, 1.527, 1.637, 1.741, 1.847,
#        1.973, 2.118, 2.268, 2.418, 2.568, 2.718, 2.868, 3.018,
#        3.168, 3.318, 3.456, 3.5]

# Run 0: 24 bins
#bins = [0.500, 0.65, 0.745, 0.849, 0.929, 1.008, 1.115, 1.213, 1.296, 1.427,
#        1.542, 1.675, 1.799, 1.943, 2.093, 2.243, 2.393, 2.543, 2.693, 2.843,
#        2.993, 3.143, 3.293, 3.443, 3.5]

# Run 1: 25 bins
#bins = [0.5, 0.537, 0.674, 0.771, 0.869, 0.949, 1.035, 1.139, 1.234, 1.329,
#        1.456, 1.575, 1.706, 1.835, 1.981, 2.131, 2.28, 2.43, 2.581, 2.731,
#        2.881, 3.03, 3.18, 3.331, 3.457, 3.5]

# Run 2: 25 bins
#bins = [0.5, 0.575, 0.698, 0.797, 0.889, 0.969, 1.062, 1.164, 1.255, 1.361,
#        1.485, 1.609, 1.737, 1.871, 2.018, 2.168, 2.318, 2.468, 2.618, 2.768,
#        2.918, 3.068, 3.218, 3.368, 3.471, 3.5]

# Run 3: 24 bins
#bins = [0.5, 0.613, 0.721, 0.823, 0.909, 0.988, 1.088, 1.189, 1.275, 1.394,
#        1.513, 1.642, 1.768, 1.907, 2.055, 2.205, 2.355, 2.506, 2.655, 2.805,
#        2.955, 3.105, 3.256, 3.405, 3.5]

# Run 0: 23 bins
#bins = [0.5, 0.65, 0.742, 0.854, 0.936, 1.018, 1.148, 1.245, 1.358, 1.469,
#        1.602, 1.747, 1.868, 2.018, 2.168, 2.318, 2.468, 2.618, 2.768, 2.918,
#        3.068, 3.218, 3.368, 3.5]

# Run 1: 24 bins
#bins = [0.5, 0.53, 0.668, 0.764, 0.87, 0.952, 1.044, 1.167, 1.268, 1.38,
#       1.496, 1.631, 1.771, 1.898, 2.048, 2.198, 2.348, 2.498, 2.648, 2.798,
#        2.948, 3.098, 3.248, 3.394, 3.5]

# Run 2: 24 bins
#bins = [0.5, 0.56, 0.687, 0.787, 0.887, 0.969, 1.07, 1.187, 1.29, 1.402,
#        1.522, 1.66, 1.795, 1.928, 2.078, 2.228, 2.378, 2.528, 2.678, 2.828,
#        2.978, 3.128, 3.278, 3.421, 3.5]

# Run 3: 24 bins
#bins = [0.5, 0.59, 0.705, 0.809, 0.903, 0.985, 1.096, 1.206, 1.313, 1.425,
#        1.549, 1.689, 1.82, 1.958, 2.108, 2.258, 2.408, 2.558, 2.708, 2.858,
#        3.008, 3.158, 3.308, 3.447, 3.5]

# Run 4: 24 bins
#bins = [0.5, 0.62, 0.724, 0.832, 0.92, 1.002, 1.122, 1.226, 1.335, 1.447,
#        1.575, 1.718, 1.844, 1.988, 2.138, 2.288, 2.438, 2.588, 2.738, 2.888,
#        3.038, 3.188, 3.338, 3.474, 3.5]

# Run 0: 26 bins
#bins = [0.5, 0.656, 0.708, 0.791, 0.851, 0.902, 0.965, 1.016, 1.109, 1.184, 1.244, 1.309, 1.406, 1.469, 1.551, 1.642, 1.74, 1.821, 1.907, 2.001, 2.117, 2.272, 2.461, 2.702, 2.962, 3.262, 3.5]

# Run 1: 27 bins
#bins = [0.5, 0.552, 0.673, 0.736, 0.811, 0.868, 0.923, 0.982, 1.047, 1.134, 1.204, 1.266, 1.341, 1.427, 1.496, 1.581, 1.675, 1.767, 1.85, 1.938, 2.04, 2.169, 2.335, 2.541, 2.789, 3.062, 3.341, 3.5]

# Run 2: 27 bins
bins = [0.5, 0.604, 0.691, 0.763, 0.831, 0.885, 0.944, 0.999, 1.078, 1.159, 1.224, 1.287, 1.374, 1.448, 1.524, 1.612, 1.707, 1.794, 1.878, 1.97, 2.078, 2.22, 2.398, 2.622, 2.875, 3.162, 3.421, 3.5]

[catalog.classification.binning.stellar_mass]
id = "lp_mass_med"                  # Column name for stellar mass
#bins = [8.5, 10.4, 10.7, 12]
bins = [8.7, 10.6, 10.9, 11.7]

# Map configurations - each section defines a new map
[maps.mips_24]
wavelength = 24.0             # Wavelength in microns
color_correction = 1.24       # Color correction factor
path_map = "$MAPSPATH/cosmos/cutouts/mips_24_GO3_sci_10.cutout.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/mips_24_GO3_unc_10.cutout.fits"

[maps.mips_24.beam]
fwhm = 5.51                   # FWHM in arcsec
area_sr = 1.328e-09          # Solid angle (1.0 if already in Jy/beam)

[maps.mips_70]
wavelength = 70.0             # Wavelength in microns
color_correction = 1.33       # Color correction factor
path_map = "$MAPSPATH/cosmos/mips/scosmos_mips_70_sci_v3.fits"
path_noise = "$MAPSPATH/cosmos/mips/scosmos_mips_70_unc_v3.fits"

[maps.mips_70.beam]
fwhm = 18.0                   # FWHM in arcsec
area_sr = 1.296e-08          # Solid angle (1.0 if already in Jy/beam)

[maps.pacs_green]
wavelength = 100.0
color_correction = 1.0
path_map = "$MAPSPATH/cosmos/cutouts/COSMOS_PACS100_20160805_img_avg.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/COSMOS_PACS100_20160805_img_avg_noise.fits"

[maps.pacs_green.beam]
fwhm = 7.49
area_sr = 2.033e-09

[maps.pacs_red]
wavelength = 160.0
color_correction = 1.0
path_map = "$MAPSPATH/cosmos/cutouts/COSMOS_PACS160_20160728_img_avg.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/COSMOS_PACS160_20160728_img_avg_noise.fits"

[maps.pacs_red.beam]
fwhm = 11.33
area_sr = 4.658e-09

[maps.spire_psw]
wavelength = 250.0
color_correction = 1.018
path_map = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PSW.signal.cutout.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PSW.noise.cutout.fits"

[maps.spire_psw.beam]
fwhm = 17.62

[maps.spire_pmw]
wavelength = 350.0
color_correction = 0.9914
path_map = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PMW.signal.cutout.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PMW.noise.cutout.fits"

[maps.spire_pmw.beam]
fwhm = 24.42

[maps.spire_plw]
wavelength = 500.0
color_correction = 0.9565
path_map = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PLW.signal.cutout.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/cosmos-uvista-hipe12_itermap_10_iterations_6.0_arcsec_pixels_PLW.noise.cutout.fits"

[maps.spire_plw.beam]
fwhm = 35.69

[maps.scuba]
wavelength = 850.0
color_correction = 1e-3
path_map = "$MAPSPATH/cosmos/cutouts/S2CLS_COSMOS_NMF_DR1_new_header.cutout.signal.fits"
path_noise = "$MAPSPATH/cosmos/cutouts/S2CLS_COSMOS_NMF_DR1_new_header.cutout.noise.fits"

[maps.scuba.beam]
fwhm = 12.1